export const profileImg =
  'https://thumbs.dreamstime.com/b/black-man-avatar-male-portrait-sunglasses-stylish-scarf-beard-modern-style-macho-user-profile-fashion-casual-urban-look-apparel-363405807.jpg';

export const placeData = [
  {
    id: 1,
    name: 'Niladri Reservoir',
    rating: 4.7,
    location: 'Tekergat, Sunamgnj',
    image: require('./src/assets/imgs/bgImg.webp'),
    visitors: [
      { id: 1, avatar: 'https://randomuser.me/api/portraits/men/1.jpg' },
      { id: 2, avatar: 'https://randomuser.me/api/portraits/women/2.jpg' },
      { id: 3, avatar: 'https://randomuser.me/api/portraits/men/3.jpg' },
      { id: 4, avatar: 'https://randomuser.me/api/portraits/women/4.jpg' },
      { id: 5, avatar: 'https://randomuser.me/api/portraits/women/4.jpg' },
    ],
    images: [
      { id: 1, img: require('./src/assets/imgs/bgImg.webp') },
      { id: 2, img: require('./src/assets/imgs/1.jpg') },
      { id: 3, img: require('./src/assets/imgs/2.jpg') },
      { id: 4, img: require('./src/assets/imgs/3.jpg') },
      { id: 5, img: require('./src/assets/imgs/4.jpg') },
    ],
    extraVisitors: 50,
    desc: 'You will get a complete travel package on the beaches.Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek',
  },
  {
    id: 2,
    name: 'Darma Reservoir',
    rating: 3.7,
    location: 'Tekergat, Sunamgnj',
    image: require('./src/assets/imgs/bgImg.webp'),
    visitors: [
      { id: 1, avatar: 'https://randomuser.me/api/portraits/men/1.jpg' },
      { id: 2, avatar: 'https://randomuser.me/api/portraits/women/2.jpg' },
      { id: 3, avatar: 'https://randomuser.me/api/portraits/men/3.jpg' },
      { id: 4, avatar: 'https://randomuser.me/api/portraits/women/4.jpg' },
      { id: 5, avatar: 'https://randomuser.me/api/portraits/men/3.jpg' },
    ],
    images: [
      { id: 1, img: require('./src/assets/imgs/bgImg.webp') },
      { id: 2, img: require('./src/assets/imgs/1.jpg') },
      { id: 3, img: require('./src/assets/imgs/2.jpg') },
      { id: 4, img: require('./src/assets/imgs/3.jpg') },
      { id: 5, img: require('./src/assets/imgs/4.jpg') },
    ],
    extraVisitors: 50,
    desc: 'You will get a complete travel package on the beaches.Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek',
  },
  {
    id: 3,
    name: 'Niladri Reservoir',
    rating: 4.7,
    location: 'Tekergat, Sunamgnj',
    image: require('./src/assets/imgs/bgImg.webp'),
    visitors: [
      { id: 1, avatar: 'https://randomuser.me/api/portraits/men/1.jpg' },
      { id: 2, avatar: 'https://randomuser.me/api/portraits/women/2.jpg' },
      { id: 3, avatar: 'https://randomuser.me/api/portraits/men/3.jpg' },
      { id: 4, avatar: 'https://randomuser.me/api/portraits/women/4.jpg' },
      { id: 5, avatar: 'https://randomuser.me/api/portraits/men/3.jpg' },
    ],
    images: [
      { id: 1, img: require('./src/assets/imgs/bgImg.webp') },
      { id: 2, img: require('./src/assets/imgs/1.jpg') },
      { id: 3, img: require('./src/assets/imgs/2.jpg') },
      { id: 4, img: require('./src/assets/imgs/3.jpg') },
      { id: 5, img: require('./src/assets/imgs/4.jpg') },
    ],
    extraVisitors: 50,
    desc: 'You will get a complete travel package on the beaches.Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek',
  },
  {
    id: 4,
    name: 'Darma Reservoir',
    rating: 3.7,
    location: 'Tekergat, Sunamgnj',
    image: require('./src/assets/imgs/bgImg.webp'),
    visitors: [
      { id: 1, avatar: 'https://randomuser.me/api/portraits/men/1.jpg' },
      { id: 2, avatar: 'https://randomuser.me/api/portraits/women/2.jpg' },
      { id: 3, avatar: 'https://randomuser.me/api/portraits/men/3.jpg' },
      { id: 4, avatar: 'https://randomuser.me/api/portraits/women/4.jpg' },
      { id: 5, avatar: 'https://randomuser.me/api/portraits/men/3.jpg' },
    ],
    images: [
      { id: 1, img: require('./src/assets/imgs/bgImg.webp') },
      { id: 2, img: require('./src/assets/imgs/1.jpg') },
      { id: 3, img: require('./src/assets/imgs/2.jpg') },
      { id: 4, img: require('./src/assets/imgs/3.jpg') },
      { id: 5, img: require('./src/assets/imgs/4.jpg') },
    ],
    extraVisitors: 50,
    desc: 'You will get a complete travel package on the beaches.Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek',
  },
];
